export const spellList = [
    "Acid Arrow",
    "Acid Splash",
    "Aid",
    "Alarm",
    "Alter Self",
    "Animal Friendship",
    "Animal Messenger",
    "Animal Shapes",
    "Animate Dead",
    "Animate Objects",
    "Antilife Shell",
    "Antimagic Field",
    "Antipathy Sympathy",
    "Arcane Eye",
    "Arcane Hand",
    "Arcane Lock",
    "Arcane Sword",
    "Arcanists Magic Aura",
    "Astral Projection",
    "Augury",
    "Awaken",
    "Bane",
    "Banishment",
    "Barkskin",
    "Beacon Of Hope",
    "Bestow Curse",
    "Black Tentacles",
    "Blade Barrier",
    "Bless",
    "Blight",
    "Blindness Deafness",
    "Blink",
    "Blur",
    "Branding Smite",
    "Burning Hands",
    "Call Lightning",
    "Calm Emotions",
    "Chain Lightning",
    "Charm Person",
    "Chill Touch",
    "Circle Of Death",
    "Clairvoyance",
    "Clone",
    "Cloudkill",
    "Color Spray",
    "Command",
    "Commune",
    "Commune With Nature",
    "Comprehend Languages",
    "Compulsion",
    "Cone Of Cold",
    "Confusion",
    "Conjure Animals",
    "Conjure Celestial",
    "Conjure Elemental",
    "Conjure Fey",
    "Conjure Minor Elementals",
    "Conjure Woodland Beings",
    "Contact Other Plane",
    "Contagion",
    "Contingency",
    "Continual Flame",
    "Control Water",
    "Control Weather",
    "Counterspell",
    "Create Food And Water",
    "Create Or Destroy Water",
    "Create Undead",
    "Creation",
    "Cure Wounds",
    "Dancing Lights",
    "Darkness",
    "Darkvision",
    "Daylight",
    "Death Ward",
    "Delayed Blast Fireball",
    "Demiplane",
    "Detect Evil And Good",
    "Detect Magic",
    "Detect Poison And Disease",
    "Detect Thoughts",
    "Dimension Door",
    "Disguise Self",
    "Disintegrate",
    "Dispel Evil And Good",
    "Dispel Magic",
    "Divination",
    "Divine Favor",
    "Divine Word",
    "Dominate Beast",
    "Dominate Monster",
    "Dominate Person",
    "Dream",
    "Druidcraft",
    "Earthquake",
    "Eldritch Blast",
    "Enhance Ability",
    "Enlarge Reduce",
    "Entangle",
    "Enthrall",
    "Etherealness",
    "Expeditious Retreat",
    "Eyebite",
    "Fabricate",
    "Faerie Fire",
    "Faithful Hound",
    "False Life",
    "Fear",
    "Feather Fall",
    "Feeblemind",
    "Find Familiar",
    "Find Steed",
    "Find The Path",
    "Find Traps",
    "Finger Of Death",
    "Fire Bolt",
    "Fire Shield",
    "Fire Storm",
    "Fireball",
    "Flame Blade",
    "Flame Strike",
    "Flaming Sphere",
    "Flesh To Stone",
    "Floating Disk",
    "Fly",
    "Fog Cloud",
    "Forbiddance",
    "Forcecage",
    "Foresight",
    "Freedom Of Movement",
    "Freezing Sphere",
    "Gaseous Form",
    "Gate",
    "Geas",
    "Gentle Repose",
    "Giant Insect",
    "Glibness",
    "Globe Of Invulnerability",
    "Glyph Of Warding",
    "Goodberry",
    "Grease",
    "Greater Invisibility",
    "Greater Restoration",
    "Guardian Of Faith",
    "Guards And Wards",
    "Guidance",
    "Guiding Bolt",
    "Gust Of Wind",
    "Hallow",
    "Hallucinatory Terrain",
    "Harm",
    "Haste",
    "Heal",
    "Healing Word",
    "Heat Metal",
    "Hellish Rebuke",
    "Heroes Feast",
    "Heroism",
    "Hideous Laughter",
    "Hold Monster",
    "Hold Person",
    "Holy Aura",
    "Hunters Mark",
    "Hypnotic Pattern",
    "Ice Storm",
    "Identify",
    "Illusory Script",
    "Imprisonment",
    "Incendiary Cloud",
    "Inflict Wounds",
    "Insect Plague",
    "Instant Summons",
    "Invisibility",
    "Irresistible Dance",
    "Jump",
    "Knock",
    "Legend Lore",
    "Lesser Restoration",
    "Levitate",
    "Light",
    "Lightning Bolt",
    "Locate Animals Or Plants",
    "Locate Creature",
    "Locate Object",
    "Longstrider",
    "Mage Armor",
    "Mage Hand",
    "Magic Circle",
    "Magic Jar",
    "Magic Missile",
    "Magic Mouth",
    "Magic Weapon",
    "Magnificent Mansion",
    "Major Image",
    "Mass Cure Wounds",
    "Mass Heal",
    "Mass Healing Word",
    "Mass Suggestion",
    "Maze",
    "Meld Into Stone",
    "Mending",
    "Message",
    "Meteor Swarm",
    "Mind Blank",
    "Minor Illusion",
    "Mirage Arcane",
    "Mirror Image",
    "Mislead",
    "Misty Step",
    "Modify Memory",
    "Moonbeam",
    "Move Earth",
    "Nondetection",
    "Pass Without Trace",
    "Passwall",
    "Phantasmal Killer",
    "Phantom Steed",
    "Planar Ally",
    "Planar Binding",
    "Plane Shift",
    "Plant Growth",
    "Poison Spray",
    "Polymorph",
    "Power Word Kill",
    "Power Word Stun",
    "Prayer Of Healing",
    "Prestidigitation",
    "Prismatic Spray",
    "Prismatic Wall",
    "Private Sanctum",
    "Produce Flame",
    "Programmed Illusion",
    "Project Image",
    "Protection From Energy",
    "Protection From Evil And Good",
    "Protection From Poison",
    "Purify Food And Drink",
    "Raise Dead",
    "Ray Of Enfeeblement",
    "Ray Of Frost",
    "Regenerate",
    "Reincarnate",
    "Remove Curse",
    "Resilient Sphere",
    "Resistance",
    "Resurrection",
    "Reverse Gravity",
    "Revivify",
    "Rope Trick",
    "Sacred Flame",
    "Sanctuary",
    "Scorching Ray",
    "Scrying",
    "Secret Chest",
    "See Invisibility",
    "Seeming",
    "Sending",
    "Sequester",
    "Shapechange",
    "Shatter",
    "Shield",
    "Shield Of Faith",
    "Shillelagh",
    "Shocking Grasp",
    "Silence",
    "Silent Image",
    "Simulacrum",
    "Sleep",
    "Sleet Storm",
    "Slow",
    "Spare The Dying",
    "Speak With Animals",
    "Speak With Dead",
    "Speak With Plants",
    "Spider Climb",
    "Spike Growth",
    "Spirit Guardians",
    "Spiritual Weapon",
    "Stinking Cloud",
    "Stone Shape",
    "Stoneskin",
    "Storm Of Vengeance",
    "Suggestion",
    "Sunbeam",
    "Sunburst",
    "Symbol",
    "Telekinesis",
    "Telepathic Bond",
    "Teleport",
    "Teleportation Circle",
    "Thaumaturgy",
    "Thunderwave",
    "Time Stop",
    "Tiny Hut",
    "Tongues",
    "Transport Via Plants",
    "Tree Stride",
    "True Polymorph",
    "True Resurrection",
    "True Seeing",
    "True Strike",
    "Unseen Servant",
    "Vampiric Touch",
    "Vicious Mockery",
    "Wall Of Fire",
    "Wall Of Force",
    "Wall Of Ice",
    "Wall Of Stone",
    "Wall Of Thorns",
    "Warding Bond",
    "Water Breathing",
    "Water Walk",
    "Web",
    "Weird",
    "Wind Walk",
    "Wind Wall",
    "Wish",
    "Word Of Recall",
    "Zone Of Truth",
  ];

  export const spellSlots = {
    classes: ['bard','cleric','wizard','druid','sorcerer', 'paladin', 'ranger', 'warlock'],
    'bard,cleric,wizard,druid,sorcerer': {  
      1: [],
      2: [],
      3: [],
      4: [],
      5: [],
      6: [],
      7: [],
      8: [],
      9: [],
      10: []

    },
    "paladin,ranger": { 
      1: [],
      2: [],
      3: [],
      4: [],
      5: [],
      6: [],
      7: [],
      8: [],
      9: [],
      10: []},
      "warlock":  {
      1: [],
      2: [],
      3: [],
      4: [],
      5: [],
      6: [],
      7: [],
      8: [],
      9: [],
      10: []
    }
  }